### ISSUE TITLE
Add format types to `CombineArchiveContentFormat`

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulators/Biosimulators_utils#87]
https://github.com/biosimulators/Biosimulators_utils/blob/6ce19360af353444bf671f39ca9998dff3c4efff/biosimulators_utils/combine/data_model.py#L161

I have encountered the following file types in PMR workspaces. Some of them might be valid formats to specify in the OMEX manifest as their own types or one of the existing types: 
- [x] HTML ( should be text?)
- [x] Adobe Illustrator
- [x]  Javascript
- [x] C source 
- [x] XML User Interface Language
- [x] RDF (text/xml? )
- [x] RST (text?)
- [x] Encapsulated PostScript (EPS)
- [ ] Exchangeable Image Format (EXF)
- [ ] cmgui, exnode, exelem ( [CMGUI files](http://physiomeproject.org/software/opencmiss/cmgui))
- [x] Doc
- [x] Docx
- [x] XLS (not XLSX) 
- [x] DLL
- [x] SO
- [ ] CONF (could be text but anything really) 
- [x] Ruby Source
- [x] C++ header
- [x] C++ Source
- [x] SVGZ (Compressed svg)
- [x] msh [Gmsh file](https://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format)
- [x] .coordinates, .connectivity (text files) 
- [ ] proj file (http://physiomeproject.org/workflow/1.0/rdf-schema#workflowproject) Seems to be a physiome specific file
- [ ] vm file (Velocity Template files)
- [x] PPT
- [x] PPTX

**Comment by jonrkarr** [comment]
I can add these. 

This package is not intended to outline an exhaustive list of formats, just common packages. A format need not be defined in this package for a manifest to be considered valid.

**Comment by bilalshaikh42** [comment]
Thanks!

 > This package is not intended to outline an exhaustive list of formats, just common packages. A format need not be defined in this package for a manifest to be considered valid.

Yup, I figured it might be easier to have one place to define all of them for the code that we write to import models from repositories. Any files that are too obscure to include in this package can certainly be left out. The wording "valid" in the original comment was confusing. "useful" would be a better term

**Comment by jonrkarr** [comment]
There's also a list in the ontologies module in biosimulations.

What is important is that each format is consistently described with the same URI, particularly for model formats. I've summarized this in the documentation. Through the ontologies module of biosimulations, this is also advertised in the biosimulations API.

**Comment by jonrkarr** [comment]
Added in 037df87791021fedf23cbf71dddd946a36d8de0a. Will be released with 0.1.153.

Notes
- Anything that doesn't have a reasonably accepted media type could use `application/octet-stream` (`http://purl.org/NET/mediatypes/application/octet-stream` in manifests)
- AI: `application/pdf`is typically used
- Conf: this isn't a single format; I added `text/x-ini` for .ini-style files. otherwise use `text/plain`
- Exchangeable Image Format (EXIF): its not a standalone format. Its typically a part of a JPEG, TIFF, or other image file formats. For .exif alone use `application/octet-stream`
- exnode, exelem: no media type appears to be defined; use `application/octet-stream`
- (Physiome) proj file: Not sure what this is; use `application/octet-stream`
- RDF: These files are probably RDF-XML. The XML encoding for RDF is typically `application/xml+rdf`.
- RST: `text/x-rst`
- SVGZ: doesn't have its own media type; see w3c/svgwg#701. Typically `image/svg+xml` is used.
- Velocity template (VTL): doesn't have a canonical media type; use `application/octet-stream`
- .coordinates, .connectivity: this is a loose format known as the XYZ format, often with the extension .xyz. Use `chemical/x-xyz`

**Comment by jonrkarr** [comment]
Also added to https://github.com/biosimulations/biosimulations/blob/dev/libs/ontology/extra-sources/src/lib/edam-biosimulations-formats.json so these formats are available through the BioSimulations API.

**Comment by jonrkarr** [comment]
Also created a few EDAM issues to request terms for the most popular of these formats.
